local resourceName = GetCurrentResourceName()
local pendingImports = {}

local function loadJsonConfig(path)
    -- Role: load and decode a JSON configuration file.
    -- Params: path (string) relative resource path.
    -- Return: table decoded config or empty table.
    -- Behavior: prints a warning when the file cannot be parsed.
    -- Security: reads only packaged resource files.
    local rawConfig = LoadResourceFile(resourceName, path)

    if not rawConfig then
        print(('[WEAZEL] Missing config file: %s'):format(path))
        return {}
    end

    local ok, decoded = pcall(json.decode, rawConfig)

    if not ok or type(decoded) ~= 'table' then
        print(('[WEAZEL] Invalid JSON in config file: %s'):format(path))
        return {}
    end

    return decoded
end

local function splitDataUrl(dataUrl)
    -- Role: split a browser data URL into mime type and raw base64 payload.
    -- Params: dataUrl (string).
    -- Return: mimeType (string|nil), payload (string|nil).
    -- Behavior: accepts only data URLs generated by the import NUI.
    -- Security: refuses malformed data URLs before any persistence step.
    local mimeType, payload = string.match(dataUrl or '', '^data:([^;]+);base64,(.+)$')
    return mimeType, payload
end

local function isAllowedMime(mimeType)
    -- Role: validate allowed journal image mime types.
    -- Params: mimeType (string).
    -- Return: boolean.
    -- Behavior: accepts PNG and JPEG only.
    -- Security: blocks unsupported or potentially unsafe file types.
    return mimeType == 'image/png' or mimeType == 'image/jpeg'
end

local function estimateBytesFromBase64(payload)
    -- Role: estimate original binary size from a base64 string.
    -- Params: payload (string).
    -- Return: integer bytes.
    -- Behavior: uses the standard 4-to-3 ratio with padding correction.
    -- Security: size is calculated server-side rather than trusting browser metadata.
    local length = #payload
    local padding = 0

    if payload:sub(-2) == '==' then
        padding = 2
    elseif payload:sub(-1) == '=' then
        padding = 1
    end

    return math.floor((length * 3) / 4) - padding
end

RegisterNetEvent('weazel_news:server:validateImport', function(data)
    -- Role: validate an imported image selected from the NUI before publication.
    -- Params: data (table) containing filename, resolution and dataUrl.
    -- Return: none.
    -- Behavior: caches one pending import per player after server-side checks.
    -- Security: validates permission, file type, payload presence and max size.
    local source = source
    local allowed, reason = WeazelPermissionService.canPublish(source)

    if not allowed then
        WeazelPermissionService.log(source, 'journal_import_refused', { reason = reason })
        TriggerClientEvent('weazel_news:client:importValidated', source, false, reason)
        return
    end

    local config = loadJsonConfig('configs/weazel_config.json')
    local filename = tostring(data.filename or '')
    local resolution = tostring(data.resolution or 'unknown')
    local mimeType, base64Payload = splitDataUrl(data.dataUrl)
    local maxBytes = (tonumber(config.MaxFileSizeMB) or 5) * 1024 * 1024

    if filename == '' or not mimeType or not base64Payload then
        TriggerClientEvent('weazel_news:client:importValidated', source, false, 'Fichier invalide ou incomplet.')
        return
    end

    if not filename:lower():match('%.png$') and not filename:lower():match('%.jpe?g$') then
        TriggerClientEvent('weazel_news:client:importValidated', source, false, 'Le journal doit etre un PNG ou un JPG.')
        return
    end

    if not isAllowedMime(mimeType) then
        TriggerClientEvent('weazel_news:client:importValidated', source, false, 'Type MIME non autorise.')
        return
    end

    local bytes = estimateBytesFromBase64(base64Payload)

    if bytes <= 0 or bytes > maxBytes then
        TriggerClientEvent('weazel_news:client:importValidated', source, false, ('Le fichier depasse la limite de %s MB.'):format(tonumber(config.MaxFileSizeMB) or 5))
        return
    end

    pendingImports[source] = {
        filename = filename,
        mimeType = mimeType,
        dataUrl = data.dataUrl,
        image = base64Payload,
        resolution = resolution,
        bytes = bytes
    }

    WeazelPermissionService.log(source, 'journal_imported', {
        filename = filename,
        mimeType = mimeType,
        resolution = resolution,
        bytes = bytes
    })

    TriggerClientEvent('weazel_news:client:importValidated', source, true, pendingImports[source])
end)

AddEventHandler('playerDropped', function()
    -- Role: clear any pending import when a player leaves the server.
    -- Params: none (uses implicit source).
    -- Return: none.
    -- Behavior: prevents abandoned base64 payloads lingering in memory.
    -- Security: cleans per-player memory state proactively.
    pendingImports[source] = nil
end)

function GetPendingWeazelImport(source)
    -- Role: expose the current pending import for the publisher flow.
    -- Params: source (number) server id.
    -- Return: table|nil cached import.
    -- Behavior: returns the import previously validated in this session.
    -- Security: pending data remains server-side until publication.
    return pendingImports[source]
end

function ClearPendingWeazelImport(source)
    -- Role: clear a player's pending import after publication or cancellation.
    -- Params: source (number) server id.
    -- Return: none.
    -- Behavior: drops cached file data from memory.
    -- Security: ensures large base64 payloads are not retained longer than needed.
    pendingImports[source] = nil
end
